Update "ContributingGuide" for latest llama.cpp
SciSharp/LLamaSharp pull request #951
Opened 2024-10-15 00:50 UTC by scritch1sm

2024-10-15 13:14 UTC, martindevans requested changes

2024-10-15 13:14 UTC, martindevans commented on docs/ContributingGuide.md
> +cmake .. -DGGML_CUDAS=ON -DBUILD_SHARED_LIBS=ON
should this be `GGML_CUDA`?

2024-10-15 13:14 UTC, martindevans commented on llama.cpp
Looks like you've committed an update to llama.cpp, can you undo that and just submit the changes to ContributingGuide.md. Thanks.

2024-10-16 03:56 UTC, scritch1sm commented on llama.cpp
ah crud.  sorry about that.  didn't notice that snuck in there.

2024-10-16 03:56 UTC, closed without merging